-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Waktu pembuatan: 08 Jan 2025 pada 09.14
-- Versi server: 10.4.28-MariaDB
-- Versi PHP: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `baliparadise`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `pura`
--

CREATE TABLE `pura` (
  `id` int(11) NOT NULL,
  `nama` varchar(255) NOT NULL,
  `deskripsi` text NOT NULL,
  `foto` varchar(255) NOT NULL,
  `lokasi` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data untuk tabel `pura`
--

INSERT INTO `pura` (`id`, `nama`, `deskripsi`, `foto`, `lokasi`) VALUES
(1, 'Pura Besakih', 'Pura Besakih merupakan pura terbesar dan tertua di Bali, yang memiliki sejarah panjang sejak abad ke-8 Masehi. Awal mula berdirinya pura ini berawal dari perjalanan spiritual seorang pertapa bernama Rsi Markandeya. Ia memimpin sekelompok pengikutnya dari Jawa ke Bali untuk membuka lahan baru di lereng Gunung Agung. Dalam prosesnya, banyak pengikutnya yang meninggal karena kondisi alam yang keras. Untuk menghindari hal serupa, Rsi Markandeya melakukan meditasi dan ritual suci, kemudian menanam sebuah paku tanah (Basuki) sebagai lambang perlindungan. Dari sinilah nama \"Besakih\" berasal.\r\nPura ini kemudian berkembang menjadi pusat keagamaan Hindu di Bali, terutama setelah konsep Tri Hita Karana harmoni antara manusia, alam, dan Tuhan mengakar kuat dalam budaya masyarakat Bali. Kini, Pura Besakih tidak hanya menjadi tempat ibadah, tetapi juga simbol spiritual dan budaya yang melibatkan berbagai ritual besar seperti Upacara Eka Dasa Rudra yang dilakukan setiap seratus tahun sekali.\r\n<br><br>\r\nPura Besakih berlokasi di Desa Besakih, Kecamatan Rendang, Kabupaten Karangasem, Bali, Indonesia, tepatnya di lereng Gunung Agung dengan ketinggian sekitar 1.000 meter di atas permukaan laut.\r\n<br><br>\r\n<b>Larangan bagi Wisatawan di Pura Besakih</b>\r\n<ul>\r\n<li>- Tidak diperbolehkan memasuki area utama pura bagi wanita yang sedang menstruasi.</li>\r\n<li>- Wajib mengenakan pakaian sopan seperti kain dan selendang yang bisa disewa di pintu masuk.</li>\r\n<li>- Dilarang berbicara keras atau menunjukkan sikap tidak hormat selama berada di area pura.</li>\r\n<li>- Tidak boleh memanjat atau menyentuh bangunan maupun tempat pemujaan.</li>\r\n<li>- Larangan membawa makanan atau minuman ke dalam pura.</li>\r\n<li>- Tidak diperkenankan mengambil foto atau video saat berlangsungnya upacara keagamaan tanpa izin.</li>\r\n<li>- Dilarang membawa hewan peliharaan ke dalam area pura.</li>\r\n', '1735556244298.jpg', 'Karangasem, Bali'),
(3, 'Pura Lempuyang', 'Pura Lempuyang adalah salah satu pura tertua di Bali dan termasuk dalam jajaran pura kahyangan jagat, yaitu pura yang dianggap sangat suci oleh umat Hindu Bali. Pura ini berada di lereng Gunung Lempuyang, Kabupaten Karangasem, Bali, pada ketinggian sekitar 1.170 meter di atas permukaan laut. Sejarahnya berakar dari keyakinan Hindu Bali bahwa Gunung Lempuyang adalah tempat bersemayamnya Dewa Iswara, salah satu manifestasi Tuhan dalam agama Hindu. Pura ini dikenal sebagai \"Gerbang Surga\" karena pemandangannya yang menakjubkan, terutama gerbang utama (Candi Bentar) yang membingkai latar belakang Gunung Agung secara sempurna.\r\nPura Lempuyang tidak hanya dianggap sebagai tempat ibadah tetapi juga sebagai tempat penyucian diri. Untuk mencapai pura utama, pengunjung harus menaiki lebih dari 1.700 anak tangga, sebuah perjalanan spiritual yang melambangkan perjuangan manusia dalam mencapai kesucian. <br> <br>\r\n\r\nPura Lempuyang berlokasi di Desa Tista, Kecamatan Abang, Kabupaten Karangasem, Bali, Indonesia. <br> <br>\r\n\r\n<b> Larangan bagi Wisatawan di Pura Lempuyang </b>\r\n\r\n<ul> <li>-Tidak diperbolehkan memasuki area pura bagi wanita yang sedang menstruasi.</li>\r\n<li>- Wajib mengenakan kain dan selendang, yang biasanya disediakan di pintu masuk. </li>\r\n<li>- Dilarang berbicara keras, bercanda, atau menunjukkan perilaku yang tidak hormat. </li>\r\n<li>- Tidak boleh membawa makanan atau minuman ke dalam area pura. </li>\r\n<li>- Dilarang mengambil foto dengan pose yang tidak sopan, terutama di area Candi Bentar.</li>\r\n<li>- Tidak diperkenankan menaiki atau memanjat gerbang maupun tempat pemujaan. </li>\r\n<li>- Larangan keras menggunakan drone tanpa izin, terutama di area suci. </li>\r\n<li>- Pengunjung yang hanya datang untuk berfoto tanpa menghormati kesakralan pura dapat ditegur atau tidak diizinkan masuk ke area tertentu. </li>\r\n<li>- Memakai pakaian yang terbuka atau tidak sopan dianggap pelanggaran berat.</li> </ul>\r\n', '1735556266854.jpg', 'Karangasem, Bali'),
(4, 'Pura Tanah Lot', 'Pura Tanah Lot adalah salah satu pura laut (Pura Segara) yang paling terkenal di Bali, yang didirikan untuk memuja Dewa Baruna, dewa laut dalam keyakinan Hindu. Sejarahnya berawal dari abad ke-16, ketika seorang pendeta bernama Dang Hyang Nirartha melakukan perjalanan spiritual menyusuri pantai selatan Bali. Ia tertarik pada keindahan sebuah batu karang besar yang menjorok ke laut, dan menganggap tempat tersebut suci. Di sana, ia bermeditasi dan membangun sebuah pura sebagai penghormatan kepada dewa laut.\r\nPura ini terletak di atas batu karang besar yang dikelilingi oleh air laut saat pasang, menciptakan pemandangan ikonik yang menarik banyak wisatawan. Tanah Lot juga merupakan bagian dari jajaran pura laut yang menjaga Bali dari energi negatif, bersama pura-pura lainnya seperti Pura Uluwatu. <br> <br>\r\n\r\nPura Tanah Lot berlokasi di Desa Beraban, Kecamatan Kediri, Kabupaten Tabanan, Bali, Indonesia. <br> <br>\r\n\r\n<b> Larangan bagi Wisatawan di Pura Tanah Lot </b>\r\n\r\n<ul> <li>- Tidak diperkenankan memasuki pura utama karena hanya digunakan untuk kegiatan ibadah umat Hindu. </li>\r\n<li>- Wajib mengenakan pakaian sopan, terutama jika mendekati area suci. </li>\r\n<li>- Dilarang memanjat atau menyentuh tempat pemujaan. </li>\r\n<li>- Tidak boleh berbicara keras atau bercanda yang tidak pantas di area pura. </li>\r\n<li>- Larangan membawa makanan dan minuman ke dalam area pura.</li>\r\n<li>- Tidak diperbolehkan berenang di sekitar pura, karena selain untuk menjaga kesucian, ombak di sekitar sangat berbahaya.</li>\r\n<li>- Dilarang mengambil foto secara tidak sopan, terutama yang dapat dianggap tidak menghormati kesucian pura.</li>\r\n<li>- Tidak boleh membuang sampah sembarangan di area pura dan sekitarnya.</li> </ul>\r\n', '1735556305999.jpg', 'Tabanan, Bali'),
(5, 'Pura Uluwatu', 'Pura Luhur Uluwatu adalah salah satu pura kahyangan jagat yang memiliki peranan penting dalam menjaga keseimbangan spiritual Pulau Bali. Pura ini terletak di ujung tebing curam setinggi sekitar 70 meter di atas Samudra Hindia, menawarkan pemandangan spektakuler matahari terbenam dan gelombang laut yang menghantam karang. Dibangun pada abad ke-11, pura ini dikaitkan dengan perjalanan spiritual Dang Hyang Nirartha, seorang pendeta Hindu yang menyebarkan ajaran Hindu Bali. Konon, Nirartha mencapai pencerahan spiritual di tempat ini sebelum \"moksa\" (penyatuan dengan Tuhan).\r\nNama \"Uluwatu\" berasal dari kata \"ulu\" yang berarti kepala atau ujung, dan \"watu\" yang berarti batu. Ini menggambarkan lokasi pura di atas batu karang yang menjorok ke laut. Pura Uluwatu tidak hanya menjadi pusat ibadah tetapi juga simbol perlindungan Bali dari energi negatif yang datang dari arah barat daya. Saat ini, pura ini juga menjadi daya tarik wisata, terutama karena pertunjukan tari kecak yang diadakan setiap sore menjelang matahari terbenam.<br><br>\r\n\r\nPura Luhur Uluwatu berlokasi di Desa Pecatu, Kecamatan Kuta Selatan, Kabupaten Badung, Bali, Indonesia. <br> <br>\r\n\r\n<b> Larangan bagi Wisatawan di Pura Luhur Uluwatu </b>\r\n\r\n<ul> <li>- Wanita yang sedang menstruasi dilarang memasuki area pura.</li>\r\n<li>- Wajib mengenakan pakaian sopan, termasuk kain dan selendang yang dapat dipinjam di pintu masuk. </li>\r\n<li>- Dilarang berbicara keras atau bercanda tidak pantas, terutama di area pura utama. </li>\r\n<li>- Tidak diperbolehkan memanjat atau menyentuh tempat pemujaan untuk menjaga kesucian pura.</li>\r\n<li>- Hati-hati terhadap monyet di sekitar area pura, karena mereka sering mengambil barang bawaan seperti kacamata, topi, atau perhiasan. </li>\r\n<li>- Dilarang membawa makanan di area pura, karena dapat menarik perhatian monyet dan menyebabkan gangguan. </li>\r\n<li>- Larangan mengambil foto dengan pose tidak sopan atau menggunakan drone tanpa izin di area pura. </li>\r\n<li>- Pengunjung tidak boleh memasuki area suci pura utama, yang hanya diperuntukkan bagi umat Hindu yang sedang beribadah. </li> <ul>\r\n\r\n', '1735725885795.jpg', 'Badung, Bali'),
(6, 'Pura Tirta Empul', 'Pura Tirta Empul adalah salah satu pura suci di Bali yang terkenal dengan kolam pemandian air suci. Pura ini dibangun pada masa Dinasti Warmadewa, sekitar abad ke-10 Masehi, di sekitar sumber mata air yang dianggap suci. Nama \"Tirta Empul\" sendiri berarti \"air suci yang muncul dari tanah,\" sesuai dengan keberadaan mata air yang mengalir ke beberapa kolam di pura ini.\r\nDalam mitologi Hindu Bali, air di Pura Tirta Empul diyakini sebagai pemberian Dewa Indra untuk melawan kekuatan jahat Raja Mayadenawa. Oleh sebab itu, mata air ini dianggap memiliki kekuatan penyucian, dan hingga saat ini digunakan dalam berbagai ritual pembersihan spiritual dan penyucian diri oleh umat Hindu Bali maupun pengunjung.\r\n<br> <br>\r\n\r\nPura Tirta Empul berlokasi di Desa Manukaya, Kecamatan Tampaksiring, Kabupaten Gianyar, Bali, Indonesia.\r\n<br> <br>\r\n\r\n<b> Larangan bagi Wisatawan di Pura di Pura Tirta Empul </b>\r\n\r\n<ul> <li>- Wanita yang sedang menstruasi dilarang memasuki area pura atau kolam suci.</li>\r\n<li>- Wajib mengenakan kain dan selendang yang dapat disewa di pintu masuk, bahkan saat akan mandi di kolam suci. </li>\r\n<li>- Dilarang membawa makanan atau minuman ke dalam area pura. </li>\r\n<li>- Tidak boleh mengambil air suci tanpa izin dari pemangku pura. </li>\r\n<li>- Larangan keras berbicara kasar atau bercanda tidak sopan di area kolam atau pura. </li>\r\n<li>- Tidak diperbolehkan memanjat atau menyentuh tempat pemujaan. </li>\r\n<li>- Wisatawan yang ingin mandi di kolam suci harus mengikuti alur dan prosedur ritual, dimulai dari pancuran pertama hingga terakhir. </li>\r\n<li>- Dilarang mengambil foto yang tidak sopan, terutama di area kolam atau tempat pemujaan. </li> </ul>\r\n', '1735728172575.jpg', 'Gianyar, Bali'),
(7, 'Pura Ulun Danu', 'Pura Ulun Danu Beratan adalah salah satu pura ikonik di Bali yang terletak di tepi Danau Beratan, Bedugul. Pura ini dibangun pada abad ke-17 oleh Raja Mengwi sebagai tempat pemujaan kepada Dewi Danu, dewi yang menguasai danau dan sungai. Danau Beratan sendiri merupakan sumber utama irigasi bagi pertanian di Bali, sehingga pura ini memiliki peran penting dalam kehidupan agraris masyarakat Bali.\r\nKompleks pura ini terdiri dari beberapa bangunan, termasuk pura utama yang berdiri di atas pulau kecil di tengah danau. Pemandangan pura yang tampak seperti \"mengapung\" di atas air menjadi salah satu daya tarik utama, terutama saat kabut tipis menyelimuti area sekitar. Pura ini juga mencerminkan hubungan harmonis antara manusia, alam, dan Tuhan sesuai konsep Tri Hita Karana.<br> <br>\r\n\r\nPura Ulun Danu Beratan terletak di Desa Candikuning, Kecamatan Baturiti, Kabupaten Tabanan, Bali, Indonesia. <br> <br>\r\n\r\n<b> Larangan bagi Wisatawan di Pura Ulun Danu Beratan </b>\r\n\r\n<ul> <li>- Tidak diperbolehkan memasuki area dalam pura utama, karena hanya digunakan untuk kegiatan ibadah.</li>\r\n<li>- Wajib mengenakan pakaian sopan saat memasuki kawasan pura. </li>\r\n<li>- Dilarang berbicara keras atau menunjukkan sikap tidak hormat di area pura. </li>\r\n<li>- Tidak boleh berenang atau memancing di area sekitar pura dan danau. </li>\r\n<li>- Dilarang membuang sampah sembarangan di kawasan pura dan sekitarnya. </li>\r\n<li>- Tidak diperkenankan menggunakan drone tanpa izin untuk menjaga kesucian dan kenyamanan pengunjung lain. </li>\r\n<li>- Larangan keras mengambil foto atau video saat ada upacara keagamaan tanpa seizin pemangku pura. </li>\r\n<li>- Tidak boleh memanjat bangunan pura atau menyentuh tempat pemujaan.</li> </ul>\r\n', '1735728266230.jpg', 'Tabanan, Bali'),
(8, 'Pura Goa Lawah', 'Pura Goa Lawah adalah salah satu pura penting di Bali yang terletak di kawasan Klungkung, tepatnya di Desa Pesinggahan. Pura ini dikenal dengan nama \"Pura Goa Lawah\" yang berarti \"Pura Goa Kelelawar,\" karena terdapat gua besar di dalam area pura yang dihuni oleh ribuan kelelawar. Pura ini memiliki sejarah panjang yang berkaitan dengan penyebaran agama Hindu di Bali.\r\nPura Goa Lawah didirikan pada abad ke-11 oleh Dang Hyang Nirartha, seorang pendeta Hindu yang sangat dihormati di Bali. Legenda mengatakan bahwa Nirartha berhenti di tempat ini dalam perjalanan spiritualnya dan melihat banyaknya kelelawar yang tinggal di gua tersebut, yang dianggap sebagai simbol energi spiritual. Oleh karena itu, pura ini dibangun untuk menghormati Dewi Danu dan Dewi Sri, yang dianggap sebagai penjaga keseimbangan alam dan kehidupan. Pura Goa Lawah juga merupakan salah satu pura yang berada di sepanjang garis pura laut di Bali, yang bertujuan menjaga keseimbangan alam dan melindungi Bali dari ancaman energi negatif. <br> <br>\r\n\r\nPura Goa Lawah terletak di Desa Pesinggahan, Kecamatan Dawan, Kabupaten Klungkung, Bali, Indonesia. <br> <br>\r\n\r\n<b> Larangan bagi Wisatawan di Pura Goa Lawah </b>\r\n\r\n<ul> <li>- Wanita yang sedang menstruasi dilarang memasuki area pura. </li>\r\n<li>- Wajib mengenakan pakaian sopan, termasuk kain dan selendang, yang dapat disewa di pintu masuk pura. <li>\r\n<li>- Dilarang berbicara keras atau bercanda yang tidak sopan, terutama di area suci. </li>\r\n<li>- Tidak diperbolehkan menyentuh tempat pemujaan atau memanjat bangunan pura. </li>\r\n<li>- Hati-hati terhadap kelelawar di dalam gua, dan hindari mengganggu mereka. </li>\r\n<li>- Tidak boleh membawa makanan atau minuman ke dalam area pura, untuk menjaga kesucian tempat tersebut. </li>\r\n<li>- Larangan keras terhadap foto atau video yang tidak menghormati tempat suci atau suasana keagamaan. </li>\r\n<li>- Pengunjung tidak diperkenankan memasuki area gua tempat kelelawar tinggal tanpa izin.</li></ul>\r\n', '1735728363727.JPG', 'Klungkung, Bali'),
(9, 'Pura Pura Saraswati', 'Pura Saraswati adalah salah satu pura yang terletak di Ubud, Bali, yang didedikasikan untuk memuja Dewi Saraswati, dewi ilmu pengetahuan, seni, dan musik dalam agama Hindu. Pura ini dibangun dengan tujuan untuk menghormati Dewi Saraswati sebagai sumber inspirasi bagi para seniman dan cendekiawan. Pura Saraswati terletak di tengah-tengah Ubud, yang dikenal sebagai pusat seni dan budaya Bali.\r\nPura ini memiliki arsitektur yang sangat indah dan terawat, dengan kolam ikan teratai yang memberikan nuansa damai dan menenangkan. Dalam agama Hindu Bali, Dewi Saraswati diyakini memberikan anugerah berupa pengetahuan dan kebijaksanaan, sehingga pura ini sering dikunjungi oleh mereka yang ingin mencari kedamaian batin dan meningkatkan kemampuan intelektual maupun kreatif. Pura Saraswati juga sering digunakan sebagai tempat upacara keagamaan dan persembahyangan oleh umat Hindu Bali. <br> <br>\r\n\r\nPura Saraswati terletak di Jalan Raya Ubud, Ubud, Gianyar, Bali, Indonesia. <br> <br>\r\n\r\n<b>Larangan bagi Wisatawan di Pura Saraswati</b> <br>\r\n\r\n<ul> <li>- Wanita yang sedang menstruasi dilarang memasuki area pura. </li>\r\n<li>- Wajib mengenakan pakaian sopan, termasuk kain dan selendang, yang dapat disewa di pintu masuk pura. </li>\r\n<li>- Dilarang berbicara keras atau bercanda yang tidak pantas di area pura. </li>\r\n<li>- Tidak boleh menyentuh tempat pemujaan atau memanjat bangunan pura. </li>\r\n<li>- Tidak diperbolehkan membawa makanan atau minuman ke dalam area pura. </li>\r\n<li>- Larangan mengambil foto atau video dengan pose yang tidak sopan, terutama di area tempat ibadah. </li>\r\n<li>- Tidak diperkenankan memasuki area yang sedang digunakan untuk upacara keagamaan tanpa izin.</li> </ul>\r\n', '1735728481484.jpg', 'Gianyar, Bali'),
(10, 'Pura Taman Ayun', 'Pura Taman Ayun adalah pura keluarga kerajaan yang terletak di Mengwi, Kabupaten Badung, Bali. Pura ini dibangun pada abad ke-17 oleh Raja I Gusti Agung Putu, sebagai tempat ibadah keluarga kerajaan Mengwi. Nama \"Taman Ayun\" sendiri berasal dari kata \"taman,\" yang berarti taman, dan \"ayun,\" yang berarti indah atau cantik. Pura ini memang dikenal dengan keindahan taman dan kolam yang mengelilingi kompleks pura, menciptakan suasana yang sangat damai dan menenangkan.\nPura Taman Ayun memiliki arsitektur yang sangat khas, dengan beberapa bangunan pura yang dikelilingi oleh kolam besar. Taman ini dibangun dengan konsep yang melambangkan keberadaan dunia yang seimbang antara alam manusia, alam dewa, dan alam leluhur. Pura ini tidak hanya berfungsi sebagai tempat ibadah, tetapi juga sebagai simbol kekuatan dan kemakmuran kerajaan Mengwi pada masa lalu. Saat ini, Pura Taman Ayun menjadi salah satu tujuan wisata yang sangat populer di Bali, dikenal dengan keindahan arsitektur, taman, dan suasana spiritual yang menenangkan. <br>\n<br>\n\nPura Taman Ayun berlokasi di Desa Mengwi, Kecamatan Mengwi, Kabupaten Badung, Bali, Indonesia. <br> <br>\n\n<b>Larangan bagi Wisatawan di Pura Taman Ayun</b> <br>\n\n<ul> <li>- Wanita yang sedang menstruasi dilarang memasuki area pura.</li>\n<li>- Wajib mengenakan pakaian sopan, termasuk kain dan selendang, yang dapat disewa di pintu masuk pura.</li>\n<li>- Dilarang berbicara keras atau bercanda yang tidak pantas di area pura.</li>\n<li>- Tidak boleh memanjat bangunan pura atau menyentuh tempat pemujaan.</li>\n<li>- Dilarang membawa makanan atau minuman ke dalam area pura.</li>\n<li>- Tidak diperbolehkan mengambil foto atau video dengan tujuan yang tidak menghormati kesucian pura.</li>\n<li>- Pengunjung tidak boleh memasuki area suci pura utama yang hanya diperuntukkan bagi umat Hindu yang sedang beribadah.</li></ul>\n', '1735730133761.jpg', 'Badung, Bali');

--
-- Indexes for dumped tables
--

--
-- Indeks untuk tabel `pura`
--
ALTER TABLE `pura`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT untuk tabel yang dibuang
--

--
-- AUTO_INCREMENT untuk tabel `pura`
--
ALTER TABLE `pura`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
